on:
  push:
    branches:
      - 'main'
    paths:
      - 'workshop_material/**'
  workflow_dispatch:
permissions:
  contents: write
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Zip Course material
      run: |
        FILE=playbooks/roles/transfer_workshop_material/files/workshop_material.zip
        if test -f "$FILE"; then
          rm playbooks/roles/transfer_workshop_material/files/workshop_material.zip
        else
          mkdir playbooks/roles/transfer_workshop_material/files/
        fi
        zip -r playbooks/roles/transfer_workshop_material/files/workshop_material.zip workshop_material
    - uses: actions/upload-artifact@v4
      with:
        name: workshop_material
        path: playbooks/roles/transfer_workshop_material/files/workshop_material.zip
    - name: Commit files
      run: |
        git config --local user.email "github@uu.nl"
        git config --local user.name "GitHub Utrecht University"
        git add .
        git commit -a -m "Update course material"
      continue-on-error: true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }} 
        github_token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
